resilience4j:
  retry:
    instances:
      test:
        max-attempts: 10
        wait-duration: 3s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.FeignException
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberofCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreException:
          - java.util.NoSuchElementException
    instances:
      test:
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 3s
        failureRateThreshold: 10
server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000